apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server  }}
  project: default
  source:
    path: velero
    helm:
      values: |
        image:
          tag: "v1.10.2
        initContainerImage:
          tag: "v1.6.1
    repoURL: {{ .Values.spec.source.repoURL  }}
    targetRevision: {{ .Values.spec.source.targetRevision  }}
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
      - CreateNamespace=true
